[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.dagster]
module_name = "social_listening"

[tool.poetry.dependencies]
python = "^3.7"
dagster = "^1.0.0"
dagster-slack = "^0.18.0"
tweepy = "^4.0.0"
requests = "^2.26.0"
